# Generated by Django 4.0.5 on 2022-06-22 06:00

from django.db import migrations, models
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_shop_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.CharField(max_length=255, verbose_name='review'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=django_google_maps.fields.AddressField(max_length=200, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='city',
            field=models.CharField(max_length=50, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
    ]
