# Generated by Django 4.0.5 on 2022-06-27 04:36

import django.core.validators
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_alter_review_review_alter_shop_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='countries',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='shop',
            name='is_closed_temporarily',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='is_open_now',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
